# NAME: ALISTAIR SALDANHA
# SAPID: 60009200024
# BATCH: K1
# EXPERIMENT-9

In [30]:
import numpy as np
# To check available >= need
def availability(i):
    for j in range(no_r):
        if(needed[i][j]>available[j]):
            return 0
    return 1

# MAIN FUNCTION
no_p = 5
no_r = 3
# Sequence stores the processes after execution
Sequence = np.zeros((no_p,),dtype=int)
# Visited stores if process of executed successfully
visited = np.zeros((no_p,),dtype=int)
# Given in the Problem
allocated = np.array([[0, 1, 0 ], [2, 0, 0], [3, 0, 2], [2, 1, 1] , [0, 0, 2]])
maximum = np.array([[7, 5, 3 ], [3, 2, 2 ], [ 9, 0, 2 ], [2, 2, 2], [4, 3, 3]])
available = np.array([3, 3, 2])
needed = maximum - allocated
# count - number of processes executed successfully
count = 0
while(count < no_p) :
    temp=0
    for i in range( no_p ):
        if( visited[i] == 0 ):
            if(availability(i)):
                Sequence[count]=i;
                print(Sequence)
                count+=1
                visited[i]=1
                temp=1
                for j in range(no_r):
                    available[j] += allocated[i][j]
    # Process is neither visited nor the resources available for its execution
    if(temp == 0):
        break
if(count < no_p):
    print('The system is Unsafe')
else:
    print("The system is Safe")
    print("Safe Sequence: ",Sequence)
    print("Available Resource:",available)

[1 0 0 0 0]
[1 3 0 0 0]
[1 3 4 0 0]
[1 3 4 0 0]
[1 3 4 0 2]
The system is Safe
Safe Sequence:  [1 3 4 0 2]
Available Resource: [10  5  7]


In [31]:
import numpy as np
# To check available >= need
def availability(i):
    for j in range(no_r):
        if(needed[i][j]>available[j]):
            return 0
    return 1

# MAIN FUNCTION
no_p = 3
no_r = 3
# Sequence stores the processes after execution
Sequence = np.zeros((no_p,),dtype=int)
# Visited stores if process of executed successfully
visited = np.zeros((no_p,),dtype=int)
# Given in the Problem
allocated = np.array([[3,2,1], [1,1,2], [4,1,2]])
maximum = np.array([[4,4,4], [3, 4, 5], [5, 2, 4]])
available = np.array([2, 3, 2])
needed = maximum - allocated
# count - number of processes executed successfully
count = 0
while(count < no_p) :
    temp=0
    for i in range( no_p ):
        if( visited[i] == 0 ):
            if(availability(i)):
                Sequence[count]=i;
                count+=1
                visited[i]=1
                temp=1
                for j in range(no_r):
                    available[j] += allocated[i][j]
    # Process is neither visited nor the resources available for its execution
    if(temp == 0):
        break
if(count < no_p):
    print('The system is Unsafe')
else:
    print("The system is Safe")
    print("Safe Sequence: ",Sequence)
    print("Available Resource:",available)

The system is Safe
Safe Sequence:  [2 0 1]
Available Resource: [10  7  7]
